language: common-lisp
sudo: yes

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis.
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

  # Install dynamodb-local.
  - mkdir /tmp/dynamodb
  - wget -O - http://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb

before_script:
  # Start dynamodb-local
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
  - git clone https://github.com/fukamachi/dexador ~/lisp/dexador

script:
  - cl -l prove -e '(or (prove:run :dyna-test) (uiop:quit -1))'
