language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=clisp

install:
  # Install cl-travis.
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

  # Install dynamodb-local.
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb

before_script:
  # Start dynamodb-local
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
  - git clone https://github.com/fukamachi/dexador ~/lisp/dexador

script:
  - cl -l prove -e '(or (prove:run :dyna-test) (uiop:quit -1))'
